# Generated by Django 5.0.6 on 2024-06-26 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=200)),
                ("book_name", models.CharField(max_length=250)),
                ("author_name", models.CharField(max_length=250)),
                ("book_number", models.IntegerField()),
                ("isbn", models.CharField(max_length=100)),
                ("publisher", models.CharField(max_length=100)),
                ("pages", models.IntegerField()),
                ("copies", models.IntegerField()),
                ("cost", models.IntegerField()),
                ("image", models.FileField(upload_to="documents/")),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="add_book",
                        to="myapp.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("subject", models.CharField(max_length=250)),
                ("feedback", models.TextField()),
                ("reply", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_student",
                        to="myapp.student",
                    ),
                ),
            ],
        ),
    ]
