# Generated by Django 5.0.6 on 2024-07-01 07:38

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_faculty_is_approved_student_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuedBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(blank=True, max_length=100)),
                ("isbn", models.CharField(max_length=13)),
                ("issued_date", models.DateField(auto_now=True)),
                ("expiry_date", models.DateField(default=myapp.models.expiry)),
            ],
        ),
        migrations.RenameField(
            model_name="faculty",
            old_name="is_approved",
            new_name="admin_approval_status",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="is_approved",
            new_name="admin_approval_status",
        ),
    ]
